update ci.yaml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,36 +1,100 @@
-# This is a basic workflow to help you get started with Actions
+# PREREQUISITES:
+# The following secrets must be stored in your repository where this Action runs:
+# AWS_ACCESS_KEY_ID
+# AWS_CLOUDFRONT_DISTRO_ID
+# AWS_S3_BUCKET_NAME
+# AWS_SECRET_ACCESS_KEY
 
 name: CI
-
-# Controls when the workflow will run
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
-  push:
-    branches: [ master ]
-  pull_request:
-    branches: [ master ]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+    branches:
+    - master
+  push:
+    branches: 
+    - master
+  pull_request:
+    branches: 
+    - master
+env:
+  # Default AWS region where S3 pushes and CloudFront invalidations will occur.
+  AWS-DEFAULT-REGION: us-east-2
+  # Name of the branch in your repository which will store your generated site.
+  SITE-BRANCH: site
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
-    # The type of runner that the job will run on
+  # In this phase, the code is pulled from master and the site rendered in Hugo. The built site is stored as an artifact for other stages.
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+    # Check out master branch from the repo.
+    - name: Checkout master branch
+      uses: actions/checkout@v2
+      with:
+        submodules: true  # Fetch Hugo themes
+        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
+        ref: master
+    # Ensure the site succeeds Hugo builds. If it fails for some reason, the pipeline will halt.
+    - name: Build site with Hugo
+      uses: lowply/build-hugo@v0.74.1
+    # If build succeeds, store the public/ dir as an artifact to be used in subsequent phases.
+    - name: Upload output public dir as artifact
+      uses: actions/upload-artifact@v1
+      with:
+        name: public
+        path: public/
+  publish:
+  # In the publish phase, the site is pushed up to a different branch which only stores the public/ folder ("site" branch) and is also delta synchronized to the S3 bucket. CloudFront invalidation happens last.
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+    # Check out the site branch this time since we have to ultimately commit those changes there.
+    - name: Checkout site branch
+      uses: actions/checkout@v2
+      with:
+        submodules: true
+        fetch-depth: 0
+        ref: ${{ env.SITE-BRANCH }}
+    # Download the artifact containing the newly built site. This overwrites the public/ dir from the check out above.
+    - name: Download artifact from build stage
+      uses: actions/download-artifact@v1
+      with:
+        name: public
+    # Add all the files/changes in public/ that were pulled down from the build stage and then commit them.
+    # The final line sets a GitHub Action output value that can be read by other steps.
+    # This function cannot store mult-line values so newline chars must be stripped.
+    - name: Commit files
+      id: can_commit
+      run: |
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add -A public/
+        commit_message=$(git commit -m "Publish generated Hugo site." -a | tr -d '\n' || true)
+        echo "::set-output name=commit_message::$commit_message"
+    # Checks if previous stage had any valid commit.
+    - name: Nothing to commit
+      id: nothing_committed
+      if: contains(steps.can_commit.outputs.commit_message, 'nothing to commit')
+      run: echo "Saw that no changes were made to Hugo site."
+    # Push those changes back to the site branch.
+    - name: Push to site branch
+      if: steps.nothing_committed.conclusion == 'skipped'
+      uses: ad-m/github-push-action@master
+      with:
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        branch: ${{ env.SITE-BRANCH }}
+#     # Store the AWS credentials on the runner.
+#     - name: Configure AWS credentials
+#       if: steps.nothing_committed.conclusion == 'skipped'
+#       uses: aws-actions/configure-aws-credentials@v1
+#       with:
+#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#         aws-region: ${{ env.AWS-DEFAULT-REGION }}
+#     - name: Delta sync site to S3 with aws cli
+#       if: steps.nothing_committed.conclusion == 'skipped'
+#       run: aws s3 sync --size-only --delete public/ s3://${{ secrets.AWS_S3_BUCKET_NAME }}
+#     # Use the aws cli tool to perform a glob invalidation of the entire site against CloudFront.
+#     - name: Invalidate cache on CloudFront
+#       if: steps.nothing_committed.conclusion == 'skipped'
+#       run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRO_ID }} --paths "/*"
